# Generated by Django 5.2.5 on 2025-09-25 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_evento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipanteDeEvento',
            fields=[
                ('participante_id', models.AutoField(db_column='participante_id', primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('pendiente', 'pendiente'), ('aceptado', 'aceptado'), ('rechazado', 'rechazado')], default='pendiente', max_length=10)),
                ('rol', models.CharField(choices=[('invitado', 'invitado'), ('organizador', 'organizador')], default='invitado', max_length=12)),
                ('agregado_en', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(db_column='evento_id', on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='core.evento', verbose_name='Evento')),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='participaciones_evento', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Participante de evento',
                'verbose_name_plural': 'Participantes de evento',
                'db_table': 'participante_de_evento',
                'ordering': ['-agregado_en'],
                'indexes': [models.Index(fields=['evento'], name='idx_part_evento'), models.Index(fields=['usuario'], name='idx_part_usuario')],
                'constraints': [models.UniqueConstraint(fields=('evento', 'usuario'), name='uq_participante_evento_usuario')],
            },
        ),
    ]
