# Generated by Django 5.2.5 on 2025-09-30 00:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_comentario_itemenwishlist_historialderegalos_like_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insignia',
            fields=[
                ('id_insignia', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Insignia')),
                ('description', models.TextField(help_text='Explica cómo se puede obtener esta insignia.', verbose_name='Descripción')),
                ('image', models.ImageField(upload_to='insignias/', verbose_name='Imagen de la Insignia')),
            ],
            options={
                'verbose_name': 'Insignia',
                'verbose_name_plural': 'Insignias',
                'db_table': 'insignia',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('conversacion_id', models.AutoField(db_column='conversacion_id', primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('directa', 'directa'), ('grupo', 'grupo'), ('evento', 'evento')], max_length=10)),
                ('nombre', models.CharField(blank=True, max_length=120, null=True)),
                ('foto_url', models.CharField(blank=True, max_length=255, null=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('activa', 'activa'), ('archivada', 'archivada')], default='activa', max_length=10)),
                ('creador', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('evento', models.ForeignKey(blank=True, db_column='evento_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones', to='core.evento')),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('mensaje_id', models.AutoField(db_column='mensaje_id', primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('texto', 'texto'), ('imagen', 'imagen'), ('archivo', 'archivo'), ('sistema', 'sistema')], default='texto', max_length=10)),
                ('contenido', models.TextField()),
                ('metadatos', models.JSONField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('editado_en', models.DateTimeField(blank=True, null=True)),
                ('eliminado', models.BooleanField(default=False)),
                ('conversacion', models.ForeignKey(db_column='conversacion_id', on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='core.conversacion')),
                ('remitente', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BloqueoDeUsuario',
            fields=[
                ('id_bloqueo', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del bloqueo')),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueado_por', to=settings.AUTH_USER_MODEL, verbose_name='Usuario bloqueado')),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueos_realizados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que bloquea')),
            ],
            options={
                'verbose_name': 'Bloqueo de Usuario',
                'verbose_name_plural': 'Bloqueos de Usuarios',
                'db_table': 'bloqueo_de_usuario',
                'ordering': ['-timestamp'],
                'constraints': [models.UniqueConstraint(fields=('blocker', 'blocked'), name='unique_user_block')],
            },
        ),
        migrations.CreateModel(
            name='InsigniaOtorgada',
            fields=[
                ('id_ins_otorgada', models.AutoField(primary_key=True, serialize=False)),
                ('date_awarded', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Otorgamiento')),
                ('insignia', models.ForeignKey(db_column='id_insignia', on_delete=django.db.models.deletion.CASCADE, related_name='otorgada_a', to='core.insignia')),
                ('user', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='insignias_otorgadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Insignia Otorgada',
                'verbose_name_plural': 'Insignias Otorgadas',
                'db_table': 'insignia_otorgada',
                'ordering': ['-date_awarded'],
                'constraints': [models.UniqueConstraint(fields=('user', 'insignia'), name='unique_user_insignia_otorgada')],
            },
        ),
        migrations.CreateModel(
            name='EntregaMensaje',
            fields=[
                ('entrega_id', models.AutoField(db_column='entrega_id', primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('entregado', 'entregado'), ('leido', 'leido')], default='entregado', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='entregas_mensaje', to=settings.AUTH_USER_MODEL)),
                ('mensaje', models.ForeignKey(db_column='mensaje_id', on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='core.mensaje')),
            ],
            options={
                'verbose_name': 'Entrega de mensaje',
                'verbose_name_plural': 'Entregas de mensaje',
                'db_table': 'entrega_mensaje',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['mensaje'], name='idx_entrega_mensaje'), models.Index(fields=['usuario', 'estado'], name='idx_entrega_usuario_estado')],
                'constraints': [models.UniqueConstraint(fields=('mensaje', 'usuario'), name='uq_entrega_msg_usuario')],
            },
        ),
        migrations.CreateModel(
            name='ParticipanteConversacion',
            fields=[
                ('participante_id', models.AutoField(db_column='participante_id', primary_key=True, serialize=False)),
                ('rol', models.CharField(choices=[('miembro', 'miembro'), ('admin', 'admin')], default='miembro', max_length=10)),
                ('unido_en', models.DateTimeField(auto_now_add=True)),
                ('conversacion', models.ForeignKey(db_column='conversacion_id', on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='core.conversacion')),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Participante de conversación',
                'verbose_name_plural': 'Participantes de conversación',
                'db_table': 'participante_conversacion',
                'ordering': ['-unido_en'],
                'indexes': [models.Index(fields=['conversacion'], name='idx_partconv_conv'), models.Index(fields=['usuario'], name='idx_partconv_usuario')],
                'constraints': [models.UniqueConstraint(fields=('conversacion', 'usuario'), name='uq_conv_usuario')],
            },
        ),
    ]
