# Generated by Django 5.2.5 on 2025-09-30 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_insignia_conversacion_mensaje_bloqueodeusuario_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversacion',
            options={'ordering': ['-actualizada_en'], 'verbose_name': 'Conversación', 'verbose_name_plural': 'Conversaciones'},
        ),
        migrations.AddField(
            model_name='conversacion',
            name='ultimo_mensaje',
            field=models.ForeignKey(blank=True, db_column='ultimo_mensaje_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversaciones_ultimas', to='core.mensaje'),
        ),
        migrations.AddIndex(
            model_name='conversacion',
            index=models.Index(fields=['tipo'], name='idx_conv_tipo'),
        ),
        migrations.AddIndex(
            model_name='conversacion',
            index=models.Index(fields=['evento'], name='idx_conv_evento'),
        ),
        migrations.AddIndex(
            model_name='conversacion',
            index=models.Index(fields=['creador'], name='idx_conv_creador'),
        ),
        migrations.AddIndex(
            model_name='conversacion',
            index=models.Index(fields=['ultimo_mensaje'], name='idx_conv_ultimo_mensaje'),
        ),
        migrations.AlterModelTable(
            name='conversacion',
            table='conversacion',
        ),
    ]
