# Generated by Django 5.2.5 on 2025-09-30 02:19

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_conversacion_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlTienda',
            fields=[
                ('id_url', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=500, verbose_name='URL de la tienda')),
                ('nombre_tienda', models.CharField(max_length=100, verbose_name='Nombre de la tienda')),
                ('es_principal', models.BooleanField(default=False, verbose_name='¿URL principal?')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Activa?')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'URL de Tienda',
                'verbose_name_plural': 'URLs de Tiendas',
                'db_table': 'url_tienda',
                'ordering': ['-es_principal', 'nombre_tienda'],
            },
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AddField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='¿Activo?'),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['id_categoria'], name='idx_producto_categoria'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['id_marca'], name='idx_producto_marca'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['activo'], name='idx_producto_activo'),
        ),
        migrations.AlterModelTable(
            name='producto',
            table='producto',
        ),
        migrations.AddField(
            model_name='urltienda',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls_tienda', to='core.producto'),
        ),
        migrations.AddIndex(
            model_name='urltienda',
            index=models.Index(fields=['producto'], name='idx_url_producto'),
        ),
        migrations.AddIndex(
            model_name='urltienda',
            index=models.Index(fields=['activo'], name='idx_url_activo'),
        ),
        migrations.AddConstraint(
            model_name='urltienda',
            constraint=models.UniqueConstraint(condition=models.Q(('es_principal', True)), fields=('producto', 'es_principal'), name='unique_url_principal_por_producto'),
        ),
    ]
