# Generated by Django 5.2.5 on 2025-10-01 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_urltienda_alter_producto_options_producto_activo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudAmistad',
            fields=[
                ('id_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('pendiente', 'pendiente'), ('aceptada', 'aceptada'), ('rechazada', 'rechazada'), ('cancelada', 'cancelada')], default='pendiente', max_length=10)),
                ('mensaje', models.CharField(blank=True, max_length=255, null=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('respondida_en', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'solicitud_amistad',
                'ordering': ['-creada_en'],
            },
        ),
        migrations.AlterModelOptions(
            name='mensaje',
            options={'ordering': ['-creado_en'], 'verbose_name': 'Mensaje', 'verbose_name_plural': 'Mensajes'},
        ),
        migrations.AddIndex(
            model_name='mensaje',
            index=models.Index(fields=['conversacion', 'creado_en'], name='idx_msg_conv_fecha'),
        ),
        migrations.AddIndex(
            model_name='mensaje',
            index=models.Index(fields=['remitente'], name='idx_msg_remitente'),
        ),
        migrations.AlterModelTable(
            name='mensaje',
            table='mensaje',
        ),
        migrations.AddField(
            model_name='solicitudamistad',
            name='emisor',
            field=models.ForeignKey(db_column='emisor_id', on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_enviadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitudamistad',
            name='receptor',
            field=models.ForeignKey(db_column='receptor_id', on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_recibidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='solicitudamistad',
            index=models.Index(fields=['receptor', 'estado'], name='idx_sol_receptor_estado'),
        ),
        migrations.AddIndex(
            model_name='solicitudamistad',
            index=models.Index(fields=['emisor', 'estado'], name='idx_sol_emisor_estado'),
        ),
        migrations.AddConstraint(
            model_name='solicitudamistad',
            constraint=models.UniqueConstraint(fields=('emisor', 'receptor'), name='uq_solicitud_emisor_receptor'),
        ),
    ]
