# Generated by Django 5.2.5 on 2025-10-02 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_solicitudamistad_alter_mensaje_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro'), ('N', 'No declarado')], default='N', max_length=1),
        ),
    ]
