# Generated by Django 5.2.5 on 2025-10-15 02:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_user_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemenwishlist',
            name='cantidad',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad deseada'),
        ),
    ]
