# Generated by Django 5.2.5 on 2025-10-16 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_itemenwishlist_cantidad'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='resena',
            name='uq_resena_usuario_producto',
        ),
        migrations.RemoveIndex(
            model_name='resena',
            name='idx_resena_producto',
        ),
        migrations.RemoveField(
            model_name='resena',
            name='id_producto',
        ),
        migrations.AddConstraint(
            model_name='resena',
            constraint=models.UniqueConstraint(fields=('id_usuario',), name='uq_resena_usuario_unica'),
        ),
    ]
