# Generated by Django 5.2.5 on 2025-10-16 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_resena_uq_resena_usuario_producto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='url_media',
        ),
        migrations.AddField(
            model_name='post',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='posts/', verbose_name='Imagen'),
        ),
    ]
