# Generated by Django 5.2.5 on 2025-10-18 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_post_url_media_post_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resena',
        ),
    ]
