# Generated by Django 5.2.5 on 2025-10-21 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_producto_precio_notificationdevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferenciasusuario',
            name='allow_push_web',
            field=models.BooleanField(default=True, verbose_name='Permitir notificaciones push en la web'),
        ),
    ]
