# Generated by Django 5.2.5 on 2025-10-22 01:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_preferenciasusuario_allow_push_web'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResenaSitio',
            fields=[
                ('id_resena', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Reseña')),
                ('calificacion', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Calificación (1–5)')),
                ('comentario', models.TextField(blank=True, verbose_name='Comentario')),
                ('fecha_resena', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de reseña')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='resenas_sitio', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Reseña del sitio',
                'verbose_name_plural': 'Reseñas del sitio',
                'db_table': 'resena_sitio',
                'ordering': ['-fecha_resena'],
                'indexes': [models.Index(fields=['id_usuario'], name='idx_rs_usuario'), models.Index(fields=['fecha_resena'], name='idx_rs_fecha')],
            },
        ),
    ]
