# Generated by Django 5.2.5 on 2025-10-23 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_resenasitio'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
