# Generated by Django 5.2.5 on 2025-10-24 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_user_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='url',
            field=models.URLField(default='mystore.com', max_length=1000, verbose_name='URL del producto'),
        ),
    ]
