# Generated by Django 5.2.5 on 2025-10-25 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_producto_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='intereses_categorias',
            field=models.ManyToManyField(blank=True, related_name='usuarios_interesados', to='core.categoria', verbose_name='Categorías de Interés'),
        ),
        migrations.AddField(
            model_name='user',
            name='intereses_marcas',
            field=models.ManyToManyField(blank=True, related_name='usuarios_interesados', to='core.marca', verbose_name='Marcas de Interés'),
        ),
    ]
