# Generated by Django 5.2.5 on 2025-10-25 03:23

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_user_intereses_categorias_user_intereses_marcas'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('secret_santa', 'Amigo Secreto')], max_length=40)),
                ('titulo', models.CharField(blank=True, default='', max_length=120)),
                ('presupuesto_fijo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado', models.CharField(default='borrador', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('ejecutado_en', models.DateTimeField(blank=True, null=True)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='core.conversacion')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.models.card_upload_to)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('share_token', models.CharField(db_index=True, editable=False, max_length=32, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SecretSantaAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('da', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ss_giver', to=settings.AUTH_USER_MODEL)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='core.conversationevent')),
                ('recibe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ss_receiver', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('evento', 'da'), ('evento', 'recibe')},
            },
        ),
    ]
