# Generated by Django 5.2.5 on 2025-10-30 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_recommendationfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='gif_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='GIF (GIPHY)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tipo_post',
            field=models.CharField(choices=[('texto', 'Texto'), ('imagen', 'Imagen'), ('video', 'Video'), ('enlace', 'Enlace'), ('gif', 'GIF')], default='texto', max_length=10, verbose_name='Tipo de post'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['gif_url'], name='idx_post_gif_url'),
        ),
    ]
