# Generated by Django 5.2.5 on 2025-11-11 00:46

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_post_gif_url_alter_post_tipo_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='id_categoria',
            field=models.ForeignKey(on_delete=models.SET(core.models.get_default_category), to='core.categoria'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id_marca',
            field=models.ForeignKey(on_delete=models.SET(core.models.get_default_brand), to='core.marca'),
        ),
    ]
