# Generated by Django 5.2.5 on 2025-11-11 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_producto_id_categoria_alter_producto_id_marca'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoExterno',
            fields=[
                ('id_producto_externo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('precio', models.PositiveIntegerField(blank=True, null=True)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.URLField(max_length=1000)),
                ('imagen', models.URLField(blank=True, max_length=1000, null=True)),
                ('fuente', models.CharField(default='Falabella', max_length=50)),
                ('fecha_extraccion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Producto Externo',
                'verbose_name_plural': 'Productos Externos',
                'db_table': 'producto_externo',
                'ordering': ['-fecha_extraccion'],
                'indexes': [models.Index(fields=['fuente'], name='idx_ext_fuente'), models.Index(fields=['nombre'], name='idx_ext_nombre')],
            },
        ),
    ]
