# Generated by Django 5.2.5 on 2025-11-11 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_productoexterno'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoexterno',
            name='producto_interno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versiones_externas', to='core.producto'),
        ),
    ]
