# Generated by Django 5.2.5 on 2025-11-18 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_productoexternofavorito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoexterno',
            name='imagen',
            field=models.URLField(blank=True, max_length=4000, null=True),
        ),
    ]
