# Generated by Django 5.2.5 on 2025-11-18 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_productoexterno_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoexterno',
            name='url',
            field=models.URLField(max_length=4000),
        ),
    ]
