# Generated by Django 5.2.5 on 2025-11-18 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_producto_imagen'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='itemenwishlist',
            name='uniq_producto_por_wishlist',
        ),
        migrations.RemoveIndex(
            model_name='itemenwishlist',
            name='idx_item_wishlist',
        ),
        migrations.RemoveIndex(
            model_name='itemenwishlist',
            name='idx_item_producto',
        ),
        migrations.RemoveIndex(
            model_name='itemenwishlist',
            name='idx_item_prioridad',
        ),
        migrations.RemoveIndex(
            model_name='itemenwishlist',
            name='idx_item_fecha_agregado',
        ),
        migrations.AddField(
            model_name='itemenwishlist',
            name='producto_externo',
            field=models.ForeignKey(blank=True, db_column='id_producto_externo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='en_wishlists_externos', to='core.productoexterno', verbose_name='Producto externo'),
        ),
        migrations.AlterField(
            model_name='itemenwishlist',
            name='fecha_agregado',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='itemenwishlist',
            name='fecha_comprado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itemenwishlist',
            name='id_producto',
            field=models.ForeignKey(blank=True, db_column='id_producto', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='en_wishlists', to='core.producto', verbose_name='Producto interno'),
        ),
        migrations.AlterField(
            model_name='itemenwishlist',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='itemenwishlist',
            constraint=models.UniqueConstraint(condition=models.Q(('id_producto__isnull', False)), fields=('id_wishlist', 'id_producto'), name='uniq_producto_interno_por_wishlist'),
        ),
        migrations.AddConstraint(
            model_name='itemenwishlist',
            constraint=models.UniqueConstraint(condition=models.Q(('producto_externo__isnull', False)), fields=('id_wishlist', 'producto_externo'), name='uniq_producto_externo_por_wishlist'),
        ),
    ]
