# Generated by Django 5.2.5 on 2025-11-21 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_remove_itemenwishlist_uniq_producto_por_wishlist_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='itemenwishlist',
            name='uniq_producto_interno_por_wishlist',
        ),
        migrations.RemoveConstraint(
            model_name='itemenwishlist',
            name='uniq_producto_externo_por_wishlist',
        ),
        migrations.AddConstraint(
            model_name='itemenwishlist',
            constraint=models.UniqueConstraint(fields=('id_wishlist', 'id_producto'), name='uniq_producto_interno_por_wishlist'),
        ),
        migrations.AddConstraint(
            model_name='itemenwishlist',
            constraint=models.UniqueConstraint(fields=('id_wishlist', 'producto_externo'), name='uniq_producto_externo_por_wishlist'),
        ),
    ]
