# Generated by Django 5.2.5 on 2025-11-21 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_remove_itemenwishlist_uniq_producto_interno_por_wishlist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.URLField(blank=True, max_length=5000, null=True),
        ),
    ]
