# Generated by Django 5.2.5 on 2025-11-21 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_user_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationevent',
            name='fecha_intercambio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha del intercambio'),
        ),
    ]
