# Generated by Django 5.2.5 on 2025-11-21 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_conversationevent_fecha_intercambio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urltienda',
            name='url',
            field=models.URLField(max_length=5000),
        ),
    ]
