version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql80_gifters
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: gifters
      MYSQL_USER: gifters_user
      MYSQL_PASSWORD: gifters_pass
    ports:
      - "3306:3306"     # si el puerto 3306 ya está ocupado en Windows, cambia a "3307:3306"
    command: [
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_0900_ai_ci",
      "--default-authentication-plugin=caching_sha2_password"
    ]
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-prootpass"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
